### ISSUE TITLE
Crashes on fiber

### ISSUE THREAD

**Issue by th3fallen** [maccuaa/formsy-react-2#5]
get the following trying to mount a form in fiber beta 
`Uncaught TypeError: this.updater.enqueueCallback is not a function`
any ideas?

![](http://th3fallen.d.pr/LWjN4c.jpg)

**Comment by you-fail-me** [comment]
@th3fallen just got the same thing. What was the reason for you?

**Comment by th3fallen** [comment]
Had two versions of react Dom do a yarn list react-dom and see what package is adding the old version
