### ISSUE TITLE
Issue with v0.20.3

### ISSUE THREAD

**Issue by AlexHenkel** [maccuaa/formsy-react-2#8]
After updating to new version `0.20.3`, I get the following error with my custom input:

```
Super expression must either be null or a function, not undefined
```

And if I do this:
```js
import Formsy from 'formsy-react-2'

console.log(Formsy)
```
the result is `{}`

After tracing a little back the error, it seems that the package is targeting the new `browser.js` file, but it's not working with that. I had to go back to v`0.20.1` for now.

Any ideas on that?

**Comment by maccuaa** [comment]
Sorry about that.  I should have been more thorough in checking out that Pull Request.  It's been fixed in 0.20.4.
